### ISSUE TITLE
This mod do not work with 1.16.5 modpack [Please help]

### ISSUE THREAD

**Issue by I3estOFF** [TonimatasDEV/PacketSizeDoublerForge#3] opened 2022-12-28 21:01 UTC
![image](https://user-images.githubusercontent.com/63112899/209871417-f3a458cc-399d-406d-90d1-6b67c25b32b6.png)

Hi i installed this mod on 1.16.5 modpack with 300+ mods and error is still here, please help fix it

**Comment by TonimatasDEV** [comment] 2022-12-29 09:02
> ![image](https://user-images.githubusercontent.com/63112899/209871417-f3a458cc-399d-406d-90d1-6b67c25b32b6.png)
> 
> Hi i installed this mod on 1.16.5 modpack with 300+ mods and error is still here, please help fix it 

Please pass the log file.

**Comment by TonimatasDEV** [comment] 2022-12-31 07:39
> ![image](https://user-images.githubusercontent.com/63112899/209871417-f3a458cc-399d-406d-90d1-6b67c25b32b6.png)
> 
> Hi i installed this mod on 1.16.5 modpack with 300+ mods and error is still here, please help fix it

Please pass the log and the list of the mods.

**Comment by TonimatasDEV** [comment] 2022-12-31 07:47
Sorry, PerWorldPlugins is temporarily abandoned due to instability and lack of compatibility with other plugins

**Comment by TonimatasDEV** [comment] 2023-01-03 01:26
When I get the list of mods, create or reopen the edition.

**Comment by Firaga123** [comment] 2023-01-07 04:04
Hi have the same issue 
this are my mods [file:///C:/Users/User/AppData/Local/Temp/Temp2_Test.zip/modlist.html](url)

**Comment by TonimatasDEV** [comment] 2023-01-07 11:02
Should be fixed in: [PacketSizeDoublerForge-1.0.6-1.16.5.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10366061/PacketSizeDoublerForge-1.0.6-1.16.5.zip)

**Comment by TonimatasDEV** [comment] 2023-01-07 11:03
> Should have been fixed in: [PacketSizeDoublerForge-1.0.6-1.16.5.zip](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10366061/PacketSizeDoublerForge-1.0.6-1.16.5.zip)

**Closed by TonimatasDEV** 2023-01-07 11:02 UTC

**Comment by BDogg2003** [comment] 2023-03-12 02:52
Having the same issue as above when others try to join my world over LAN
![image](https://user-images.githubusercontent.com/756
[mods.txt](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10949885/mods.txt)
31346/224521499-b9d66936-410d-40df-b89c-779793aee119.png)

**Comment by TonimatasDEV** [comment] 2023-03-12 19:22
> Having the same issue as above when others try to join my world over LAN ![packet_issue](https://user-images.githubusercontent.com/75631346/224521611-4192fe2a-4725-4e81-b577-dd957e5c6366.jpg)
> 
> [mods.txt](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10949886/mods.txt)

This is not my problem, this is caused by minecraft timeout. Use this mods: https://www.curseforge.com/minecraft/mc-mods/timeoutfixes

**Comment by BDogg2003** [comment] 2023-03-12 20:00
> > Having the same issue as above when others try to join my world over LAN ![packet_issue](https://user-images.githubusercontent.com/75631346/224521611-4192fe2a-4725-4e81-b577-dd957e5c6366.jpg)
> > [mods.txt](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10949886/mods.txt)
> 
> This is not my problem, this is caused by minecraft timeout. Use this mods: https://www.curseforge.com/minecraft/mc-mods/timeoutfixes

apologies, i attached the wrong screenshot from a different pack, the files were named similarly on my pc. (I changed the file name)
here is the proper screenshot:

![netty handler](https://user-images.githubusercontent.com/75631346/224570130-62b9906c-cbda-40c1-89fd-c44c25f30003.png)

**Comment by TonimatasDEV** [comment] 2023-03-12 20:02
> > > Having the same issue as above when others try to join my world over LAN ![packet_issue](https://user-images.githubusercontent.com/75631346/224521611-4192fe2a-4725-4e81-b577-dd957e5c6366.jpg)
> > > [mods.txt](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10949886/mods.txt)
> > 
> > 
> > This is not my problem, this is caused by minecraft timeout. Use this mods: https://www.curseforge.com/minecraft/mc-mods/timeoutfixes
> 
> apologies, i attached the wrong screenshot from a different pack, the files were named similarly on my pc. (I changed the file name) here is the proper screenshot:
> 
> ![netty handler](https://user-images.githubusercontent.com/75631346/224570130-62b9906c-cbda-40c1-89fd-c44c25f30003.png)

Install conectivity mod

**Comment by editor-syntax** [comment] 2023-08-20 10:41
> > > > Having the same issue as above when others try to join my world over LAN ![packet_issue](https://user-images.githubusercontent.com/75631346/224521611-4192fe2a-4725-4e81-b577-dd957e5c6366.jpg)
> > > > [mods.txt](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10949886/mods.txt)
> > > 
> > > 
> > > This is not my problem, this is caused by minecraft timeout. Use this mods: https://www.curseforge.com/minecraft/mc-mods/timeoutfixes
> > 
> > 
> > apologies, i attached the wrong screenshot from a different pack, the files were named similarly on my pc. (I changed the file name) here is the proper screenshot:
> > ![netty handler](https://user-images.githubusercontent.com/75631346/224570130-62b9906c-cbda-40c1-89fd-c44c25f30003.png)
> 
> Install conectivity mod

Same issues. I did everything, what's next on connectivity?

**Comment by TonimatasDEV** [comment] 2023-08-20 11:20
> apologies, i attached the wrong screenshot from a different pack, the files were named similarly on my pc. (I changed the file name) here is the proper screenshot:

You have the latest version of PacketFixer?

**Comment by TonimatasDEV** [comment] 2023-08-20 14:00
> > > > > Having the same issue as above when others try to join my world over LAN ![packet_issue](https://user-images.githubusercontent.com/75631346/224521611-4192fe2a-4725-4e81-b577-dd957e5c6366.jpg)
> > > > > [mods.txt](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10949886/mods.txt)
> > > > 
> > > > 
> > > > This is not my problem, this is caused by minecraft timeout. Use this mods: https://www.curseforge.com/minecraft/mc-mods/timeoutfixes
> > > 
> > > 
> > > apologies, i attached the wrong screenshot from a different pack, the files were named similarly on my pc. (I changed the file name) here is the proper screenshot:
> > > ![netty handler](https://user-images.githubusercontent.com/75631346/224570130-62b9906c-cbda-40c1-89fd-c44c25f30003.png)
> > 
> > 
> > Install conectivity mod
> 
> Same issues. I did everything, what's next on connectivity?

I uploaded a new version on CurseForge and Modrinth fixin this problem.

**Comment by editor-syntax** [comment] 2023-08-20 14:28
> > > > > > Having the same issue as above when others try to join my world over LAN ![packet_issue](https://user-images.githubusercontent.com/75631346/224521611-4192fe2a-4725-4e81-b577-dd957e5c6366.jpg)
> > > > > > [mods.txt](https://github.com/TonimatasDEV/PacketSizeDoublerForge/files/10949886/mods.txt)
> > > > > 
> > > > > 
> > > > > This is not my problem, this is caused by minecraft timeout. Use this mods: https://www.curseforge.com/minecraft/mc-mods/timeoutfixes
> > > > 
> > > > 
> > > > apologies, i attached the wrong screenshot from a different pack, the files were named similarly on my pc. (I changed the file name) here is the proper screenshot:
> > > > ![netty handler](https://user-images.githubusercontent.com/75631346/224570130-62b9906c-cbda-40c1-89fd-c44c25f30003.png)
> > > 
> > > 
> > > Install conectivity mod
> > 
> > 
> > Same issues. I did everything, what's next on connectivity?
> 
> I uploaded a new version on CurseForge and Modrinth fixin this problem.

Alr, I’ll let you know
