### ISSUE TITLE
payload may not be larger still appears 

### ISSUE THREAD

**Issue by heyy-bbooii** [TonimatasDEV/PacketSizeDoublerForge#7] opened 2023-04-23 16:18 UTC
Installed on both client and server 1.18.2
and the client still gets the payload may not be larger then 32767 bytes

**Comment by StormDragon-64** [comment] 2023-05-23 23:33
It appears that the code was straight up just removed from the mod even though it existed in older versions
But the older versions crash the game

**Comment by TonimatasDEV** [comment] 2023-05-24 13:46
> It appears that the code that fixes the 32k payload too large error was straight up just removed from the 1.18.2 version of the mod even though it existed in older versions But the older versions crash the game

This packet causes the crash, this is the cause of this packet does not exist.

**Comment by StormDragon-64** [comment] 2023-05-24 14:56
The packet doesn't cause a crash, it just kicks you from the server your connected to.

**Comment by TonimatasDEV** [comment] 2023-05-25 23:17
Fixed in 1.0.8

**Closed by TonimatasDEV** 2023-05-25 23:17 UTC
